name: 'Cloudbase Autolabeller'
description: |
  One-stop solution for managing all your labels with a crystal-clear config.
author: Cloudbase Solutions Srl (@cloudbase)


inputs:
  token:
    description: |
      GitHub token to use for the labelling actions. ('${ secrets.GITHUB_TOKEN }')
      Can be a 'classic' token or a 'fine-grained' token with full repo/issue/PR access.
    default: ${{ github.token }}
  target:
    description: |
      Target for the labelling action.
      Can be the full URL or resource path of the repo or repo object, such as:
        - myuser/myrepo
        - muyser/myrepo/pull/N
        - myuser/myrepo/issues/N
    required: false
  target-from-action-env:
    description: |
      The '${ toJSON(github) }' variable present in GitHub actions to extract the target.
      Runs triggered on the repo will result in the labelling of the whole repo.
      Runs triggered on PRs/Issues will only result in the labelling of said item.
    required: false
  command:
    description: |
      The labelling command to run. Options are 'generate', 'sync', and 'purge'.
    default: sync
  config-path:
    description: |
      Path to the labels configuration file within your repository.
      Default is '.github/autolabels.yml'
    default: .github/autolabels.yml

outputs:
  # Can be referenced using ${{ action_id.outputs.labels }}
  labels:
    description: |
      JSON listing the label definitions which were added/modified for the given target.

runs:
  using: 'docker'
  # NOTE: Dockerfile's entrypoint automatically sources all inputs from env.
  image: 'docker://ghcr.io/aznashwan/github-autolabeler:main'

branding:
  icon: 'bookmark'
  color: 'purple'
