# Workflow for automatically labelling the autolabeler repo.

name: Autolabels Action Sync

on:
  workflow_dispatch:                    # manual triggers from Actions menu
  push:                                 # triggers on pushes to repo branches
    branches: [main]                    # triggers on pushes to 'main'
    tags: ['v*.*.*']                    # triggers on certain tags
  issues:                               # triggers on issue-related operations
    types: [opened, edited, closed]     # C_UD operations on the issue
  pull_request:                         # triggers on PR-related operations
    branches: [main]                    # PRs must have been opened against 'main'
    types: [opened, edited, reopened]   # triggers on PRs being (re)opened/edited
  issue_comment:                        # triggers on *both* PR/issue comments
    types: [created, edited, deleted]   # C_UD operations on any comments

jobs:
  autolabel:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Run autolabelling"
        id: autolabelling
        uses: aznashwan/github-autolabeler@main
        with:
          config-path: "./autolabels.yml"
          target-from-action-env: ${{ toJSON(github) }}
          command: sync

      - name: "Echo labels"
        run: echo "${{ steps.autolabelling.labels }}"
