# Workflow for automatically labelling the autolabeler repo.

name: Auto-labelling.

on:
  workflow_dispatch:
  push:
    branches: [main]


jobs:
  autolabel:
    runs-on: ubuntu-latest
    container: ghcr.io/aznashwan/github-autolabeler:main

    steps:
      - name: Checkout.
        uses: actions/checkout@v3

      - name: "Run autolabelling."
        run: |
          github-autolabeler \
            --github-token ${{ secrets.GITHUB_TOKEN }} \
            --label-definitions-file "autolabels.yml" \
            sync
            ${{ github.repository }}
