# Workflow for automatically labelling the autolabeler repo.

name: Auto-labelling.

permissions:
  contents: read
  issues: write
  pull-requests: write
  # NOTE: required to pull image if fork is private.
  packages: read

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  autolabel:
    runs-on: ubuntu-latest
    container: ghcr.io/aznashwan/github-autolabeler:main

    steps:
      - name: Checkout.
        uses: actions/checkout@v3

      - name: "Run autolabelling."
        run: |
          github-autolabeler \
            --github-token ${{ secrets.GITHUB_TOKEN }} \
            --label-definitions-file "autolabels.yml" \
            ${{ github.repository }} \
            sync
